& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'EnvironmentBox.Name' = 'EnvironmentBox'
'TextBox2.Name' = 'TextBox2'
'DirectoryPermissionsBox.Name' = 'DirectoryPermissionsBox'
'Button1.Name' = 'Button1'
'TextBox1.Name' = 'TextBox1'
'DirectoryPermissions.Name' = 'DirectoryPermissions'
'StatusStrip1.TrayLocation' = New-Object -TypeName System.Drawing.Point -ArgumentList @(17, 17)
'GroupBox1.Name' = 'GroupBox1'
'Label2.Name' = 'Label2'
'usgovbutton.Name' = 'usgovbutton'
'Label1.Name' = 'Label1'
'GroupPermissionsBox.Name' = 'GroupPermissionsBox'
'LoginStatusLabel.Name' = 'LoginStatusLabel'
'RadioButton1.Name' = 'RadioButton1'
'StatusStrip1.Name' = 'StatusStrip1'
'GroupPermissions.Name' = 'GroupPermissions'
'statusBar.Name' = 'statusBar'
'USDoDButton.Name' = 'USDoDButton'
'ComboBox1.Name' = 'ComboBox1'
'GlobalButton.Name' = 'GlobalButton'
'ExitButton.Name' = 'ExitButton'
'Label3.Name' = 'Label3'
'ChinaButton.Name' = 'ChinaButton'
'Label4.Name' = 'Label4'
'$this.Name' = 'Form1'
'RadioButton2.Name' = 'RadioButton2'
'TextBox3.Name' = 'TextBox3'
'ComboBox2.Name' = 'ComboBox2'
'ToolStripStatusLabel1.Name' = 'ToolStripStatusLabel1'
}
}