& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'Label1.Name' = 'Label1'
'TextBox3.Name' = 'TextBox3'
'MailText.Name' = 'MailText'
'TextBox2.Name' = 'TextBox2'
'Label5.Name' = 'Label5'
'GroupTypes.Name' = 'GroupTypes'
'Label2.Name' = 'Label2'
'DisplayNameText.Name' = 'DisplayNameText'
'Label3.Name' = 'Label3'
'GroupTypeText.Name' = 'GroupTypeText'
'TextBox1.Name' = 'TextBox1'
'$this.Name' = 'Form2'
'Label4.Name' = 'Label4'
'ExpirationDateTime.Name' = 'ExpirationDateTime'
'MembershipRuleText.Name' = 'MembershipRuleText'
'Mail.Name' = 'Mail'
'ExpirationDateTimeText.Name' = 'ExpirationDateTimeText'
'Button1.Name' = 'Button1'
'MembershipRule.Name' = 'MembershipRule'
'DisplayName.Name' = 'DisplayName'
'TextBox5.Name' = 'TextBox5'
'TextBox4.Name' = 'TextBox4'
'GroupObjectIDText.Name' = 'GroupObjectIDText'
}
}