& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'TextBox2.Name' = 'TextBox2'
'Label5.Name' = 'Label5'
'GroupTypes.Name' = 'GroupTypes'
'Button1.Name' = 'Button1'
'GroupObjectIDText.Name' = 'GroupObjectIDText'
'Mail.Name' = 'Mail'
'StatusStrip1.Name' = 'StatusStrip1'
'MailText.Name' = 'MailText'
'MembershipRuleText.Name' = 'MembershipRuleText'
'MembershipRule.Name' = 'MembershipRule'
'GroupTypeText.Name' = 'GroupTypeText'
'commit.Name' = 'commit'
'Label2.Name' = 'Label2'
'exit.Name' = 'exit'
'GroupMembersName.Name' = 'GroupMembersName'
'TextBox3.Name' = 'TextBox3'
'Label1.Name' = 'Label1'
'TextBox5.Name' = 'TextBox5'
'$this.Name' = 'Form2'
'DisplayNameText.Name' = 'DisplayNameText'
'GroupMembers.Name' = 'GroupMembers'
'LicenseLabel.Name' = 'LicenseLabel'
'GroupMemberView.Name' = 'GroupMemberView'
'StatusLabel.Name' = 'StatusLabel'
'DisplayName.Name' = 'DisplayName'
'TextBox4.Name' = 'TextBox4'
'LicenseList.Name' = 'LicenseList'
'StatusStrip1.TrayLocation' = New-Object -TypeName System.Drawing.Point -ArgumentList @(17, 17)
'Label3.Name' = 'Label3'
'TextBox1.Name' = 'TextBox1'
'ExpirationDateTimeText.Name' = 'ExpirationDateTimeText'
'Label4.Name' = 'Label4'
'ExpirationDateTime.Name' = 'ExpirationDateTime'
'GroupMembersView.Name' = 'GroupMembersView'
}
}